
server:
  port: 8767

spring:
  application:
    name: springcloud-feign-zdg

    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: LEGACYHTML5
      cache: false
      encoding: utf-8
      servlet:
        content-type: text/html


eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka
      #熔断器
#feign:
#  hystrix:
#    enabled: true

#    thymeleaf:
#      content-type: text/html
#      cache: false
#      mode: LEGACYHTML5