server:
  port: 80

spring:
  application:
    name: zyk-feign
    redis:
      host: localhost
      port: 6379
      timeout: 20000
      maxIdle: 300
      maxWaitMillis: 1000
      testOnBorrow: true
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    content-type: text/html
    cache: false
    mode: LEGACYHTML5
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
