server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: zyk-provider

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhangyk?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  data:
    mongodb:
      host: localhost
      port: 27017
      database: 1809a
jedis :
  pool :
    host : localhost
    port : 6379
    config :
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis : 100000